const CAN_READ_ALL_COURSES = "CAN_READ_ALL_COURSES";
const CAN_UPDATE_ALL_COURSES = "CAN_UPDATE_ALL_COURSES";
const CAN_DELETE_ALL_COURSES = "CAN_DELETE_ALL_COURSES";
const CAN_CREATE_COURSES = "CAN_CREATE_COURSES";
const CAN_UPDATE_OWN_COURSES = "CAN_UPDATE_OWN_COURSES";
//files
const CAN_DELETE_ALL_FILES = "CAN_DELETE_ALL_FILES";
const CAN_UPLOAD_FILES = "CAN_UPLOAD_FILES";
const CAN_DELETE_OWN_FILES = "CAN_DELETE_OWN_FILES";
const CAN_UPDATE_FILES = "CAN_UPDATE_FILES";
const CAN_READ_FINANCIAL_STATISTICS = "CAN_READ_FINANCIAL_STATISTICS";
//role
const CAN_APPLY_ROLE_OWNER = "CAN_APPLY_ROLE_OWNER";
const CAN_APPLY_ROLE_ADMIN = "CAN_APPLY_ROLE_ADMIN";
const CAN_APPLY_ROLE_AUTHOR = "CAN_APPLY_ROLE_AUTHOR";
const CAN_APPLY_ROLE_ORDINARY = "CAN_APPLY_ROLE_ORDINARY";
//users
const CAN_READ_USERS_LIST = "CAN_READ_USERS_LIST";
//orders
const CAN_READ_ORDERS = "CAN_READ_ORDERS";
const CAN_READ_USERS_ORDERS = "CAN_READ_USERS_ORDERS";
//voucher
const CAN_CREATE_VOUCHER = "CAN_CREATE_VOUCHER";
const CAN_UPDATE_VOUCHER = "CAN_UPDATE_VOUCHER";
const CAN_DELETE_VOUCHER = "CAN_DELETE_VOUCHER";
//category
const CAN_CREATE_CATEGORY = "CAN_CREATE_CATEGORY";
const CAN_UPDATE_CATEGORY = "CAN_UPDATE_CATEGORY";
const CAN_DELETE_CATEGORY = "CAN_DELETE_CATEGORY";
const CAN_LIST_VOUCHER = "CAN_LIST_VOUCHER";
export const PERMISSIONS = {
  CAN_READ_ALL_COURSES,
  CAN_UPDATE_ALL_COURSES,
  CAN_DELETE_ALL_COURSES,
  CAN_CREATE_COURSES,
  CAN_UPDATE_OWN_COURSES,
  CAN_DELETE_ALL_FILES,
  CAN_UPDATE_FILES,
  CAN_UPLOAD_FILES,
  CAN_DELETE_OWN_FILES,
  CAN_READ_FINANCIAL_STATISTICS,
  CAN_APPLY_ROLE_OWNER,
  CAN_APPLY_ROLE_ADMIN,
  CAN_APPLY_ROLE_AUTHOR,
  CAN_APPLY_ROLE_ORDINARY,
  CAN_READ_USERS_LIST,
  CAN_READ_ORDERS,
  CAN_READ_USERS_ORDERS,
  CAN_CREATE_VOUCHER,
  CAN_UPDATE_VOUCHER,
  CAN_DELETE_VOUCHER,
  CAN_CREATE_CATEGORY,
  CAN_UPDATE_CATEGORY,
  CAN_DELETE_CATEGORY,
  CAN_LIST_VOUCHER,
};
export const AUTHOR_PERMISSIONS = [
  CAN_CREATE_COURSES,
  CAN_UPDATE_OWN_COURSES,
  CAN_UPDATE_ALL_COURSES,
  CAN_UPLOAD_FILES,
  CAN_DELETE_OWN_FILES,
  CAN_DELETE_ALL_FILES,
  CAN_UPDATE_FILES,
];

export const ADMIN_PERMISSIONS = [
  CAN_READ_ALL_COURSES,
  CAN_UPDATE_ALL_COURSES,
  CAN_DELETE_ALL_COURSES,
  CAN_CREATE_COURSES,
  CAN_UPDATE_OWN_COURSES,
  CAN_DELETE_ALL_FILES,
  CAN_UPDATE_FILES,
  CAN_UPLOAD_FILES,
  CAN_DELETE_OWN_FILES,
  CAN_READ_FINANCIAL_STATISTICS,
  CAN_APPLY_ROLE_ADMIN,
  CAN_APPLY_ROLE_AUTHOR,
  CAN_APPLY_ROLE_ORDINARY,
  CAN_READ_USERS_LIST,
  CAN_READ_ORDERS,
  CAN_READ_USERS_ORDERS,
  CAN_CREATE_VOUCHER,
  CAN_UPDATE_VOUCHER,
  CAN_DELETE_VOUCHER,
  CAN_CREATE_CATEGORY,
  CAN_UPDATE_CATEGORY,
  CAN_DELETE_CATEGORY,
  CAN_LIST_VOUCHER,
];

export const OWNER_PERMISSIONS = [...ADMIN_PERMISSIONS, CAN_APPLY_ROLE_OWNER];
